devices:
  flybox-home-192-168-1-3:
    credentials: {}
    description: Auto-discovered generic
    device_type: generic
    enabled_protocols:
    - rest
    host: 192.168.1.3
    name: flybox.home
    retry_count: 3
    timeout: 10
  snowden-home-192-168-1-100:
    credentials: {}
    description: Auto-discovered generic
    device_type: generic
    enabled_protocols:
    - rest
    host: 192.168.1.100
    name: Snowden.home
    retry_count: 3
    timeout: 10
global_settings:
  cache_ttl: 300
  default_retry_count: 3
  default_timeout: 10
  max_concurrent_queries: 10
  rest_default_port: 443
  snmp_default_port: 161
  ssh_default_port: 22
