---
# Description: Comprehensive device health check
- name: Network Device Health Check
  hosts: network_devices
  gather_facts: false
  vars:
    check_interfaces: "{{ check_interfaces | default(true) }}"
    check_memory: "{{ check_memory | default(true) }}"
    check_cpu: "{{ check_cpu | default(true) }}"
    check_temperature: "{{ check_temperature | default(true) }}"
  
  tasks:
    - name: Check device connectivity
      ping:
      register: ping_result
    
    - name: Display connectivity status
      debug:
        msg: "{{ inventory_hostname }} is {{ 'reachable' if ping_result.ping == 'pong' else 'unreachable' }}"
    
    - name: Get device information
      ios_command:
        commands: show version
      register: version_info
      when: device_type in ['router', 'switch']
    
    - name: Display device information
      debug:
        msg: "{{ version_info.stdout[0] }}"
      when: device_type in ['router', 'switch'] and version_info.stdout[0] is defined
    
    - name: Check interface status
      ios_command:
        commands: show interfaces
      register: interface_status
      when: device_type in ['router', 'switch'] and check_interfaces
    
    - name: Parse interface status
      set_fact:
        interfaces: "{{ interface_status.stdout[0] | regex_findall('(\\w+\\d+/\\d+)\\s+is\\s+(up|down|administratively down)') }}"
      when: device_type in ['router', 'switch'] and check_interfaces and interface_status.stdout[0] is defined
    
    - name: Display interface status
      debug:
        msg: "Interface {{ item[0] }} is {{ item[1] }}"
      loop: "{{ interfaces }}"
      when: device_type in ['router', 'switch'] and check_interfaces and interfaces is defined
    
    - name: Check memory usage
      ios_command:
        commands: show memory statistics
      register: memory_stats
      when: device_type in ['router', 'switch'] and check_memory
    
    - name: Display memory usage
      debug:
        msg: "{{ memory_stats.stdout[0] }}"
      when: device_type in ['router', 'switch'] and check_memory and memory_stats.stdout[0] is defined
    
    - name: Check CPU usage
      ios_command:
        commands: show processes cpu
      register: cpu_stats
      when: device_type in ['router', 'switch'] and check_cpu
    
    - name: Display CPU usage
      debug:
        msg: "{{ cpu_stats.stdout[0] }}"
      when: device_type in ['router', 'switch'] and check_cpu and cpu_stats.stdout[0] is defined
    
    - name: Check temperature
      ios_command:
        commands: show environment temperature
      register: temp_stats
      when: device_type in ['router', 'switch'] and check_temperature
    
    - name: Display temperature
      debug:
        msg: "{{ temp_stats.stdout[0] }}"
      when: device_type in ['router', 'switch'] and check_temperature and temp_stats.stdout[0] is defined
    
    - name: Check server health
      block:
        - name: Get system load
          shell: uptime
          register: system_load
          when: device_type == 'server'
        
        - name: Get memory usage
          shell: free -h
          register: memory_usage
          when: device_type == 'server'
        
        - name: Get disk usage
          shell: df -h
          register: disk_usage
          when: device_type == 'server'
        
        - name: Display server health
          debug:
            msg: |
              System Load: {{ system_load.stdout }}
              Memory Usage: {{ memory_usage.stdout }}
              Disk Usage: {{ disk_usage.stdout }}
          when: device_type == 'server'
    
    - name: Health check summary
      debug:
        msg: "Health check completed for {{ inventory_hostname }}" 