---
# Description: Simple ping test for connectivity
- name: Ping Test
  hosts: all
  gather_facts: false
  vars:
    ping_count: "{{ ping_count | default(3) }}"
  
  tasks:
    - name: Test connectivity with ping
      ping:
      register: ping_result
    
    - name: Display ping result
      debug:
        msg: "{{ inventory_hostname }} is {{ 'reachable' if ping_result.ping == 'pong' else 'unreachable' }}"
    
    - name: Test network connectivity
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        timeout: 5
      register: port_test
      ignore_errors: yes
    
    - name: Display port test result
      debug:
        msg: "SSH port (22) is {{ 'open' if port_test is defined and port_test.state == 'started' else 'closed' }} on {{ inventory_hostname }}"
    
    - name: Ping test summary
      debug:
        msg: "Ping test completed for {{ inventory_hostname }} - Status: {{ 'SUCCESS' if ping_result.ping == 'pong' else 'FAILED' }}" 