---
# Description: Check print server health and services
- name: Print Server Health Check
  hosts: all
  gather_facts: false
  vars:
    check_ports: "{{ check_ports | default([9100, 631, 515]) }}"
    test_print_service: "{{ test_print_service | default(true) }}"
  
  tasks:
    - name: Check basic connectivity
      ping:
      register: ping_result
    
    - name: Display connectivity status
      debug:
        msg: "{{ inventory_hostname }} connectivity: {{ 'SUCCESS' if ping_result.ping == 'pong' else 'FAILED' }}"
    
    - name: Check print service ports
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ item }}"
        timeout: 5
      register: port_results
      loop: "{{ check_ports }}"
      ignore_errors: yes
    
    - name: Display port status
      debug:
        msg: "Port {{ item.item }} ({{ 'LPD' if item.item == 9100 else 'IPP' if item.item == 631 else 'LPR' if item.item == 515 else 'Unknown' }}): {{ 'OPEN' if item.state == 'started' else 'CLOSED' }}"
      loop: "{{ port_results }}"
    
    - name: Test print service response
      uri:
        url: "http://{{ ansible_host }}:631/printers/"
        method: GET
        status_code: [200, 401, 403]
        timeout: 10
      register: print_service_test
      when: test_print_service and 631 in check_ports
      ignore_errors: yes
    
    - name: Display print service status
      debug:
        msg: "Print service (IPP): {{ 'RESPONDING' if print_service_test.status == 200 else 'AUTHENTICATION_REQUIRED' if print_service_test.status in [401, 403] else 'NOT_RESPONDING' }}"
      when: test_print_service and 631 in check_ports and print_service_test is defined
    
    - name: Check CUPS service status (Linux)
      service:
        name: cups
        state: started
      register: cups_status
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
      ignore_errors: yes
    
    - name: Display CUPS service status
      debug:
        msg: "CUPS service: {{ 'RUNNING' if cups_status.state == 'started' else 'STOPPED' }}"
      when: (ansible_os_family == "RedHat" or ansible_os_family == "Debian") and cups_status is defined
    
    - name: Check print spool directory
      stat:
        path: /var/spool/cups
      register: spool_dir
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
      ignore_errors: yes
    
    - name: Display spool directory status
      debug:
        msg: "Print spool directory: {{ 'EXISTS' if spool_dir.stat.exists else 'MISSING' }}"
      when: (ansible_os_family == "RedHat" or ansible_os_family == "Debian") and spool_dir is defined
    
    - name: Get print queue status
      shell: lpstat -p
      register: print_queues
      when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"
      ignore_errors: yes
    
    - name: Display print queue status
      debug:
        msg: "Print queues: {{ print_queues.stdout_lines if print_queues.stdout_lines else 'No queues found' }}"
      when: (ansible_os_family == "RedHat" or ansible_os_family == "Debian") and print_queues is defined
    
    - name: Check Windows Print Service
      win_service:
        name: Spooler
        state: started
      register: windows_spooler
      when: ansible_os_family == "Windows"
      ignore_errors: yes
    
    - name: Display Windows print service status
      debug:
        msg: "Windows Print Spooler: {{ 'RUNNING' if windows_spooler.state == 'started' else 'STOPPED' }}"
      when: ansible_os_family == "Windows" and windows_spooler is defined
    
    - name: Print server health summary
      debug:
        msg: |
          Print Server Health Summary for {{ inventory_hostname }}:
          - Connectivity: {{ 'OK' if ping_result.ping == 'pong' else 'FAILED' }}
          - LPD Port (9100): {{ 'OPEN' if port_results | selectattr('item', 'equalto', 9100) | selectattr('state', 'equalto', 'started') | list | length > 0 else 'CLOSED' }}
          - IPP Port (631): {{ 'OPEN' if port_results | selectattr('item', 'equalto', 631) | selectattr('state', 'equalto', 'started') | list | length > 0 else 'CLOSED' }}
          - LPR Port (515): {{ 'OPEN' if port_results | selectattr('item', 'equalto', 515) | selectattr('state', 'equalto', 'started') | list | length > 0 else 'CLOSED' }} 